Repository T0madon/mini-asaas, pull requests merged in 2025-07, with the labels that each got.

#41 Feat: payment controller service
  grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
  grails-app/domain/com/mini/asaas/Payment/Payment.groovy
  grails-app/services/com/mini/asaas/payment/PaymentService.groovy
  src/main/groovy/com/mini/asaas/payment/BillingType.groovy
  src/main/groovy/com/mini/asaas/payment/PaymentRepository.groovy
  src/main/groovy/com/mini/asaas/payment/PaymentSaveAdapter.groovy
  src/main/groovy/com/mini/asaas/utils/BigDecimalUtils.groovy
Labels: Backend

#43 Feat: payment delete
  grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
  grails-app/services/com/mini/asaas/payment/PaymentService.groovy
  src/main/groovy/com/mini/asaas/payment/PaymentStatus.groovy
Labels: Backend

#51 Feat: payment restore
  grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
  grails-app/services/com/mini/asaas/payment/PaymentService.groovy
Labels: Backend, AGUARDANDO PR PREDECESSOR

#52 Feat: payment receive
  grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
  grails-app/services/com/mini/asaas/payment/PaymentService.groovy
  src/main/groovy/com/mini/asaas/payment/PaymentStatus.groovy
Labels: Backend, AGUARDANDO PR PREDECESSOR

#55 Feat: payment show
  grails-app/assets/stylesheets/payment/receipt.css
  grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
  grails-app/i18n/messages.properties
  grails-app/services/com/mini/asaas/payment/PaymentService.groovy
  grails-app/views/payment/receipt.gsp
  grails-app/views/payment/show.gsp
  src/main/groovy/com/mini/asaas/payment/PaymentStatus.groovy
  src/main/groovy/com/mini/asaas/utils/DomainErrorUtils.groovy
Labels: Frontend, Backend, AGUARDANDO PR PREDECESSOR

#56 Feat: payer restore pagination
  grails-app/controllers/com/mini/asaas/BaseController.groovy
  grails-app/controllers/com/mini/asaas/payer/PayerController.groovy
  grails-app/services/com/mini/asaas/payer/PayerService.groovy
  grails-app/services/com/mini/asaas/payment/PaymentService.groovy
  grails-app/views/payer/index.gsp
  grails-app/views/payer/showDeleted.gsp
  grails-app/views/templates/_pages.gsp
Labels: Frontend, Backend

#58 refact: payment-payer-restore
  grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
  grails-app/views/payer/showDeleted.gsp
  grails-app/views/payment/show.gsp
Labels: Frontend, Backend, AGUARDANDO PR PREDECESSOR

#59 Feat: payment job overdue
  build.gradle
  grails-app/conf/application.yml
  grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
  grails-app/jobs/com/mini/asaas/OverduePaymentJob.groovy
  grails-app/services/com/mini/asaas/payment/PaymentService.groovy
Labels: Backend

#63 Refact: show rule errors
  grails-app/controllers/com/mini/asaas/payer/PayerController.groovy
  grails-app/controllers/com/mini/asaas/payment/CreatePaymentController.groovy
  grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
  grails-app/services/com/mini/asaas/payer/PayerService.groovy
  grails-app/services/com/mini/asaas/payment/PaymentService.groovy
  grails-app/views/createPayment/index.gsp
  grails-app/views/payer/create.gsp
  grails-app/views/payer/show.gsp
  grails-app/views/payer/showDeleted.gsp
  grails-app/views/payment/show.gsp
  src/main/groovy/com/mini/asaas/payer/PayerRepository.groovy
  src/main/groovy/com/mini/asaas/utils/Utils.groovy
Labels: Frontend, Backend, AGUARDANDO PR PREDECESSOR

#64 Feat/user create view
  grails-app/assets/javascripts/form-step-control.js
  grails-app/assets/javascripts/radio_control.js
  grails-app/assets/stylesheets/create.css
  grails-app/controllers/com/mini/asaas/user/UserController.groovy
  grails-app/views/user/signUp.gsp
  grails-app/views/user/templates/_addressStep.gsp
  grails-app/views/user/templates/_identityStep.gsp
  src/main/groovy/com/mini/asaas/customer/adapters/CustomerSaveAdapter.groovy
Labels: Frontend, Backend
